name: 'pytorch_mnist_random_mlp'
task: 'classification'
input_dim: (28, 28)
num_classes: 10
save_model: False

SYSTEM:
  use_cpu: false

BACKBONE:
  network: 'mlp'

CLASSIFIER:
  classifier: "softmax"

LOSS:
  loss: 'cross_entropy'

DATASET:
  dataset: 'mnist'

TRAIN:
  max_epochs: 14
  batch_size: 64
  initial_lr: 1.0
  lr_scheduler: "step_down"
  step_down_gamma: 0.7
  step_down_on_epoch: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


TEST:
  batch_size: 1000