name: 'mnist_naive_auto_encoder'
task: 'auto_encoder'
input_dim: (28, 28)
num_classes: 10
save_model: True

SYSTEM:
  use_cpu: false

BACKBONE:
  network: 'naive_auto_encoder'

CLASSIFIER:
  classifier: "identity"

LOSS:
  loss: 'mse'

DATASET:
  dataset: 'mnist'

TRAIN:
  max_epochs: 14
  batch_size: 64
  initial_lr: 1.0
  lr_scheduler: "step_down"
  step_down_gamma: 0.78
  step_down_on_epoch: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


TEST:
  batch_size: 1000