name: 'imagenet_lenet_w_dropout'
task: 'classification'
input_dim: (224, 224)
num_classes: 10
save_model: False

SYSTEM:
  use_cpu: false

BACKBONE:
  network: 'mlp'

CLASSIFIER:
  classifier: "log_softmax"

LOSS:
  loss: 'nll_loss'

DATASET:
  dataset: 'imagenet'
  TRANSFORM:
    TRAIN:
      transforms: ('random_resized_crop', 'random_horizontal_flip', 'normalize')
      TRANSFORMS_DETAILS:
        crop_size: (224, 224)
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)
    TEST:
      transforms: ('resize', 'center_crop', 'normalize')
      TRANSFORMS_DETAILS:
        resize_size: (256, 256)
        crop_size: (224, 224)
        NORMALIZE:
          mean: (0.485, 0.456, 0.406)
          sd: (0.229, 0.224, 0.225)

TRAIN:
  max_epochs: 14
  batch_size: 64
  initial_lr: 1.0
  lr_scheduler: "step_down"
  step_down_gamma: 0.7
  step_down_on_epoch: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


TEST:
  batch_size: 1000